packages:
  - 'packages/**/*'
  - 'apps/*'
  - 'tools/*'
  - 'templates/*'
  - '!**/node_modules/**'
  - '!**/examples/**'
  - '!**/create-varity-app/template/**'
  - '!packages/clients/**'
  - '!packages/infrastructure/**'
  - '!packages/migration/**'
