export const PATTERNS_REFERENCE = `
# Varity SaaS Template -- Architecture & Patterns

> **⚠️ Known Beta Limitations** — the following issues are intentional and documented in \`KNOWN_ISSUES.md\` in every scaffolded project. Do not attempt to fix them; they will be resolved in future releases. The full list is reproduced here so you can reference it without leaving your AI coding tool:
>
> 1. **Payments are mock in beta** — all checkout flows complete instantly with no real charge; live payments are coming post-beta.
> 2. **Static export only — no SSR/API routes** — \`next.config.js\` uses \`output: 'export'\`, so \`getServerSideProps\`, \`app/api/\` routes, and dynamic server rendering are unsupported. If you need API routes, switch \`hosting\` to \`"dynamic"\` in \`varity.config.json\` and remove \`output: 'export'\` from \`next.config.js\`.
> 3. **Brief nav flash on dashboard hard refresh** — the dashboard layout mounts auth after hydration; a quick redirect flash is visible on hard refresh. This is expected and does not affect normal navigation or the user experience in production.
> 4. **First Load JS ~690 kB on dashboard routes** — this is expected. The auth and UI framework account for most of the bundle. Next.js code-splits per route so users only download what each page needs; the total is not loaded at once.
> 5. **Build logs show \`[Varity Database] Using shared development database\`** — this is normal in dev and during \`varity_build\`. Your data is isolated from other developers. After deploying with \`varitykit app deploy\`, your app gets a private dedicated database.
> 6. **Build shows \`⚠ Next.js inferred your workspace root\`** — appears when your project lives inside a larger directory that has its own \`package-lock.json\` (e.g. a monorepo or cloud IDE workspace). It does not affect your build output. To suppress it, add \`outputFileTracingRoot: __dirname\` to \`next.config.js\`:
>    \`\`\`js
>    const nextConfig = {
>      outputFileTracingRoot: __dirname,  // ← add this line
>      output: 'export',
>      // ...rest of config
>    };
>    \`\`\`
>    Projects created with \`varity_init\` have this set automatically.

## Project File Structure

\`\`\`
src/
  app/
    layout.tsx              # Root layout: <html>, <body>, <Providers>
    page.tsx                # Landing page (public, no auth)
    login/page.tsx          # Login page with PrivyStack
    not-found.tsx           # Custom 404
    globals.css             # Tailwind base styles
    dashboard/
      layout.tsx            # Auth-protected shell: PrivyStack > PrivyProtectedRoute > DashboardShell
      page.tsx              # Dashboard home: KPIs, getting-started checklist, quick actions
      projects/page.tsx     # Full CRUD: list + detail view with nested tasks
      tasks/page.tsx        # Cross-project task list with status cycling + filters
      team/page.tsx         # Team member management (invite, role change, remove)
      settings/page.tsx     # User preferences (theme, notifications, privacy)
  components/
    providers.tsx           # Global providers (ToastProvider only -- no auth at root)
    dashboard/              # DashboardStats, RecentActivity
    landing/                # Hero, Features, Pricing, HowItWorks, CTA, Testimonials
    shared/                 # Navbar, Footer
  lib/
    varity.ts               # Single re-export: \`export { db } from '@varity-labs/sdk'\`
    database.ts             # Typed collection accessors (projects, tasks, teamMembers, userSettings)
    hooks.ts                # React hooks: useProjects, useTasks, useTeam, useUserSettings, useCurrentUser
    constants.ts            # APP_NAME, NAVIGATION_ITEMS, status/priority/role option arrays
    utils.ts                # formatDate, formatDateShort, formatRelativeDate, cn, downloadCSV, isValidEmail
  services/
    dashboardService.ts     # REST API client stub — not used by the default data layer; you can safely ignore this file unless you need to call an external REST API
  types/
    index.ts                # Project, Task, TeamMember, UserSettings interfaces
.env.example                # Zero-config env vars (all optional for dev)
next.config.js              # Static export, unoptimized images, trailing slash
package.json                # @varity-labs/sdk, @varity-labs/ui-kit, @varity-labs/types, next, react, lucide-react
KNOWN_ISSUES.md             # Template limitations: payments are mock, no SSR, nav flash on refresh
varity.config.json          # Auto-generated by varity_init; commit this file
\`\`\`

## varity.config.json

\`varity.config.json\` is auto-generated by \`varity_init\` and auto-updated by \`varity_add_collection\`. **Commit this file** — it is used by \`varitykit deploy\` to configure hosting and database.

\`\`\`json
{
  "name": "my-app",
  "version": "1.0.0",
  "framework": "nextjs",
  "hosting": "static",
  "build": {
    "command": "npm run build",
    "output": "out"
  },
  "database": {
    "provider": "varity",
    "collections": ["projects", "tasks", "team_members"]
  }
}
\`\`\`

**Fields:**
- \`name\` — Project name (used as the app identifier on deploy). Set automatically by \`varity_init\` from the project name you provide. If it ever shows the wrong value, you can safely edit it here.
- \`version\` — App version string
- \`framework\` — Always \`nextjs\` for SaaS template projects
- \`hosting\` — \`static\` (global CDN, default) or \`dynamic\` (cloud compute, for apps with API routes or SSR)
- \`build.command\` — Command to build the app (e.g. \`npm run build\`)
- \`build.output\` — Output directory (e.g. \`out\` for Next.js static export)
- \`database.provider\` — Always \`varity\`
- \`database.collections\` — List of collection names used by your app; updated automatically by \`varity_add_collection\`

**When to change \`hosting\`:**
- Keep it as \`"static"\` (the default) if your app uses \`output: 'export'\` in \`next.config.js\`. This is the fastest and cheapest option — your app is served from a global edge network.
- Change it to \`"dynamic"\` only if you add API routes (\`app/api/\`) or server-side rendering to your app. Dynamic hosting runs your app as a live process with dedicated CPU and RAM.
- \`varity_deploy\` auto-detects the right mode from \`next.config.js\` even if you don't change this field — so in practice, you rarely need to edit it manually.

Commit this file. The \`name\` and \`hosting\` fields can be edited manually if needed. Use \`varity_add_collection\` to register new collections — it updates \`database.collections\` automatically.

## Built-in Collection Names (Reserved)

> **⚠️ Name Collision Warning** — the template ships with 4 collections already defined. If you call \`varity_add_collection\` with any of these names you will get a \`COLLECTION_EXISTS\` error.
>
> | Reserved name | Hook | Usage |
> |--------------|------|-------|
> | \`projects\` | \`useProjects()\` | Project management (built-in dashboard page) |
> | \`tasks\` | \`useTasks()\` | Task tracking, linked to projects |
> | \`team_members\` | \`useTeam()\` | Team roster and roles |
> | \`user_settings\` | \`useUserSettings()\` | Per-user preferences |
>
> **Always use different names for custom collections.** For example, if your app needs task-like items, call them \`crm_tasks\`, \`support_tickets\`, or \`action_items\` instead of \`tasks\`.
> The \`varity_init\` response also lists these names for quick reference.

## Data Layer Chain

The template uses a 3-file chain for all data access:

**Step 1: lib/varity.ts** -- SDK entry point
\`\`\`ts
export { db } from '@varity-labs/sdk';
\`\`\`

**Step 2: lib/database.ts** -- Typed collection accessors
\`\`\`ts
import { db } from './varity';
import type { Project, Task, TeamMember, UserSettings } from '../types';

export const projects    = () => db.collection<Project>('projects');
export const tasks       = () => db.collection<Task>('tasks');
export const teamMembers = () => db.collection<TeamMember>('team_members');
export const userSettings = () => db.collection<UserSettings>('user_settings');
\`\`\`

**Step 3: lib/hooks.ts** -- React hooks with optimistic updates
\`\`\`ts
import { projects, tasks } from './database';

// Each hook returns: { data, loading, error, create, update, remove, refresh }
export function useProjects(): UseCollectionReturn<Project> { ... }
export function useTasks(projectId?: string): UseCollectionReturn<Task> { ... }
export function useTeam(): UseCollectionReturn<TeamMember> { ... }
export function useUserSettings() { ... }
export function useCurrentUser() { ... }
\`\`\`

Hooks use optimistic updates: UI updates immediately, rolls back on error.

## Type Definitions (types/index.ts)

\`\`\`ts
export interface Project {
  id: string;
  name: string;
  description: string;
  status: 'active' | 'paused' | 'completed';
  owner: string;
  members: string[];
  dueDate: string;
  createdAt: string;
}

export interface Task {
  id: string;
  projectId: string;
  title: string;
  description?: string;
  status: 'todo' | 'in_progress' | 'done';
  priority: 'low' | 'medium' | 'high';
  assignee?: string;
  dueDate?: string;
  createdAt: string;
}

export interface TeamMember {
  id: string;
  name: string;
  email: string;
  role: 'admin' | 'member' | 'viewer';
  avatarUrl?: string;
  joinedAt: string;
}

export interface UserSettings {
  id: string;
  user_id: string;
  theme: 'light' | 'dark' | 'system';
  email_notifications: boolean;
  marketing_emails: boolean;
  product_updates: boolean;
  date_format: string;
  timezone: string;
  language: string;
  dashboard_layout: 'comfortable' | 'compact';
  two_factor_enabled: boolean;
  analytics_enabled: boolean;
  cookies_enabled: boolean;
  updated_at: string;
}
\`\`\`

## CRUD Page Pattern

Every CRUD page follows this structure (extracted from projects/page.tsx):

\`\`\`tsx
'use client';

import { useState } from 'react';
import { DataTable, EmptyState, KPICard } from '@varity-labs/ui-kit';
import { Button, Input, Textarea, Select, Dialog, ConfirmDialog, useToast } from '@varity-labs/ui-kit';
import { useProjects, useCurrentUser } from '@/lib/hooks';
import { PRIORITY_OPTIONS, PROJECT_STATUS_OPTIONS } from '@/lib/constants';
import { formatDate, downloadCSV } from '@/lib/utils';
import type { Project } from '@/types';

const EMPTY_FORM = { name: '', description: '', status: 'active' as Project['status'] };

export default function MyPage() {
  const toast = useToast();
  const { email } = useCurrentUser();
  const { data: items, loading, error, create, update, remove, refresh } = useProjects();

  // Dialog state
  const [createOpen, setCreateOpen] = useState(false);
  const [form, setForm] = useState(EMPTY_FORM);
  const [submitting, setSubmitting] = useState(false);

  // Create handler
  async function handleCreate() {
    if (!form.name.trim()) return;
    setSubmitting(true);
    try {
      await create({ name: form.name.trim(), ...otherFields });
      toast.success('Created successfully');
      setCreateOpen(false);
    } catch {
      toast.error('Failed to create');
    } finally {
      setSubmitting(false);
    }
  }

  // Table columns
  const columns = [
    { key: 'name', header: 'Name', sortable: true },
    { key: 'status', header: 'Status', render: (v: string) => <StatusBadge status={v} /> },
  ];

  return (
    <div className="space-y-6">
      {/* Header with title + action button */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Items</h1>
          <p className="mt-1 text-sm text-gray-600">Description here.</p>
        </div>
        <Button onClick={() => setCreateOpen(true)} icon={<Plus className="h-4 w-4" />}>New Item</Button>
      </div>

      {/* Create dialog */}
      <Dialog open={createOpen} onClose={() => setCreateOpen(false)} title="Create Item">
        <div className="space-y-4">
          <Input label="Name" required value={form.name} onChange={...} />
          <Button onClick={handleCreate} loading={submitting}>Create</Button>
        </div>
      </Dialog>

      {/* Error banner with retry */}
      {error && (
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3">
          <p className="text-sm text-red-700">Failed to load.</p>
          <button onClick={refresh} className="underline">Retry</button>
        </div>
      )}

      {/* Empty state or data table */}
      {!loading && items.length === 0 ? (
        <EmptyState title="No items yet" description="Create your first item." action={{ label: 'Create', onClick: () => setCreateOpen(true) }} />
      ) : (
        <div className="rounded-xl border border-gray-200 bg-white shadow-sm">
          <DataTable columns={columns} data={items} loading={loading} pagination pageSize={10} hoverable />
        </div>
      )}
    </div>
  );
}
\`\`\`

## Dashboard Layout & Auth

\`\`\`tsx
// dashboard/layout.tsx wraps all /dashboard/* pages
export default function DashboardRootLayout({ children }) {
  return (
    <PrivyStack
      appId={process.env.NEXT_PUBLIC_PRIVY_APP_ID}
      loginMethods={['email', 'google']}
      appearance={{ theme: 'light', accentColor: '#2563EB', logo: '/logo.svg' }}
    >
      <PrivyProtectedRoute fallback={<RedirectToLogin />}>
        <DashboardLayout
          navigation={NAVIGATION_ITEMS}
          user={{
            name: currentUser.name,
            email: currentUser.email,
          }}
        >
          {children}
        </DashboardLayout>
      </PrivyProtectedRoute>
    </PrivyStack>
  );
}
\`\`\`

> **Note:** The generated \`dashboard/layout.tsx\` wraps this pattern in a local \`DashboardShell\` component with a defensive \`try { require() } catch {}\` import to gracefully handle missing UI Kit dependencies. This is intentional — it ensures the app renders even if the UI Kit package fails to resolve. You can safely ignore it when reading the code.

Auth is ONLY loaded in the dashboard layout, not at the root. The landing page loads instantly.

## Providers Pattern (components/providers.tsx)

\`\`\`tsx
'use client';
import { ReactNode } from 'react';
import { ToastProvider } from '@varity-labs/ui-kit';

export function Providers({ children }: { children: ReactNode }) {
  return <ToastProvider>{children}</ToastProvider>;
}
\`\`\`

Root layout uses \`<Providers>\` for global toast. Auth (PrivyStack) is only in dashboard/layout.tsx.

## next.config.js Required Settings

\`\`\`js
const nextConfig = {
  output: 'export',               // Static export for Varity hosting
  images: { unoptimized: true },   // Required for static export
  trailingSlash: true,             // Required for static file hosting
  basePath: process.env.NEXT_PUBLIC_BASE_PATH || '',
  webpack: (config, { isServer, dev }) => {
    config.resolve.fallback = {
      ...config.resolve.fallback,
      '@react-native-async-storage/async-storage': false,  // Suppress spurious peer-dep warning
    };
    if (!dev && !isServer) {
      config.devtool = false;  // Avoid 35MB eval-source-map chunks
    }
    return config;
  },
};
\`\`\`

All three settings (\`output: 'export'\`, \`images: { unoptimized: true }\`, \`trailingSlash: true\`) are required.

## Development Server

Run the dev server with \`varity_dev_server\`. It auto-selects an available port:

- **Default port:** 3000
- **Auto-selection:** If port 3000 is already in use, the server picks the next available port (e.g., \`http://localhost:3031\`), reports the actual URL, and **automatically saves the chosen port to \`varity.config.json\`** so future starts always use the same port — no need to pass \`port: 3031\` manually each time.
- **Tutorials and docs** that reference \`localhost:3000\` may need to be adjusted if your dev server starts on a different port.
- **Pinning a port manually:** Add a \`"dev": { "port": 3031 }\` field to \`varity.config.json\`, or pass \`port: 3031\` when calling \`varity_dev_server\`.

## Environment Variables (.env.example)

\`\`\`
# ZERO CONFIG: Leave everything blank! Auth and database work immediately
# using shared development credentials. No setup required.
# For production: varitykit app deploy injects all credentials automatically.

NEXT_PUBLIC_PRIVY_APP_ID=           # Auth (optional -- dev credentials auto-used)
NEXT_PUBLIC_VARITY_APP_TOKEN=       # Database auth token (optional -- dev token auto-used)
NEXT_PUBLIC_VARITY_DB_PROXY_URL=    # Database proxy URL (optional -- defaults to https://varity.app)
NEXT_PUBLIC_VARITY_APP_ID=          # App ID (generated by varitykit app deploy)
\`\`\`

> **Note on \`NEXT_PUBLIC_VARITY_DB_PROXY_URL\`:** You do not need to set this manually. It is only required if you are running your own DB proxy instance. The \`db\` singleton falls back to \`https://varity.app\` when this variable is unset.

## Key Dependencies (package.json)

\`\`\`json
{
  "dependencies": {
    "@varity-labs/sdk": "^2.0.0-beta.7",
    "@varity-labs/types": "^2.0.0-beta.4",
    "@varity-labs/ui-kit": "^2.0.0-beta.7",
    "lucide-react": "^0.400.0",
    "next": "^15.0.0",
    "react": "^18.3.0",
    "react-dom": "^18.3.0"
  },
  "devDependencies": {
    "tailwindcss": "^3.4.0",
    "typescript": "^5.0.0",
    "autoprefixer": "^10.0.0",
    "postcss": "^8.0.0"
  }
}
\`\`\`

### @varity-labs/types vs src/types/index.ts

There are two type sources in a Varity project — they serve different purposes:

| Source | What it contains | When to use |
|--------|-----------------|-------------|
| \`@varity-labs/types\` | SDK infrastructure types (NavigationItem, UserInfo, ComponentProps, etc.) | Imported automatically by \`@varity-labs/ui-kit\` internals. Rarely imported directly in app code. |
| \`src/types/index.ts\` | **Your app's data types** (Project, Task, Invoice, etc.) | Import these in your components and hooks. Use \`varity_add_collection\` to generate new types here. |

**In practice:** You define your data types in \`src/types/index.ts\`. The \`@varity-labs/types\` package is a peer dependency of the UI kit and is installed to prevent TypeScript errors in the UI kit's type definitions. You typically don't import from it directly.

## Constants Pattern (lib/constants.ts)

\`\`\`ts
import type { NavigationItem } from '@varity-labs/ui-kit';

export const APP_NAME = 'My App'; // ← Set by varity_init to your project name; customize as needed

export const NAVIGATION_ITEMS: NavigationItem[] = [
  { label: 'Dashboard', icon: 'dashboard', path: '/dashboard' },
  { label: 'Projects',  icon: 'folder',    path: '/dashboard/projects' },
  { label: 'Tasks',     icon: 'list',      path: '/dashboard/tasks' },
  { label: 'Team',      icon: 'people',    path: '/dashboard/team' },
  // ↓ varity_add_collection inserts new entries immediately before Settings
  { label: 'Settings',  icon: 'settings',  path: '/dashboard/settings' },
];

// Valid icon values for NavigationItem.icon (Material Design icon names):
// Core set (used in the default template):
// 'dashboard'           → grid/home icon
// 'folder'              → folder icon (projects, files, categories)
// 'list'                → list/lines icon (tasks, items, records)
// 'people'              → group/team icon (users, members, staff)
// 'settings'            → gear icon (settings, configuration, preferences)
// 'trending_up'         → upward chart icon (deals, revenue, pipeline, growth)
// 'tag'                 → tag icon (clients, contacts, customers, labels)
//
// Auto-selected by varity_add_collection (also fully supported):
// 'receipt'             → receipt/invoice icon (invoices, payments, bills, transactions)
// 'inventory'           → box/inventory icon (products, items, catalog, listings)
// 'shopping_cart'       → cart icon (orders, purchases, subscriptions)
// 'event'               → calendar-event icon (events, appointments, meetings, bookings)
// 'bar_chart'           → bar chart icon (reports, analytics, metrics, stats)
// 'description'         → document icon (documents, files, notes, articles)
// 'confirmation_number' → ticket icon (tickets, support issues, bugs)
// 'campaign'            → megaphone icon (campaigns, announcements)
// 'notifications'       → bell icon (notifications, alerts)
// 'calendar'            → calendar icon (schedules, dates, deadlines)
// 'inbox'               → inbox icon (messages, requests)
// 'chart'               → chart icon (data, visualizations)
// 'star'                → star icon (favorites, featured, highlights)
// 'search'              → magnifier icon (search, discovery, lookup)
//
// Any other Material Design icon name also works — see https://fonts.google.com/icons
// varity_add_collection auto-selects an icon based on the collection name.
// To customize, edit the generated entry in NAVIGATION_ITEMS above.

export const PRIORITY_OPTIONS = [
  { value: 'low', label: 'Low' },
  { value: 'medium', label: 'Medium' },
  { value: 'high', label: 'High' },
] as const;

export const TASK_STATUS_OPTIONS = [
  { value: 'todo', label: 'To Do' },
  { value: 'in_progress', label: 'In Progress' },
  { value: 'done', label: 'Done' },
] as const;

export const PROJECT_STATUS_OPTIONS = [
  { value: 'active', label: 'Active' },
  { value: 'paused', label: 'Paused' },
  { value: 'completed', label: 'Completed' },
] as const;
\`\`\`

## UI Kit Components Used

From \`@varity-labs/ui-kit\`:
- Layout: \`DashboardLayout\`, \`CommandPalette\`
- Data: \`DataTable\`, \`KPICard\`, \`EmptyState\`
- Forms: \`Button\`, \`Input\`, \`Textarea\`, \`Select\`
- Feedback: \`Dialog\`, \`ConfirmDialog\`, \`useToast\`, \`ToastProvider\`
- Badges: \`ProjectStatusBadge\`, \`TaskStatusBadge\`, \`PriorityBadge\`
- Auth: \`PrivyStack\`, \`PrivyProtectedRoute\`, \`usePrivy\`

Icons come from \`lucide-react\` (Plus, Pencil, Trash2, Download, FolderKanban, etc).

## Adding Database Collections

Use \`varity_add_collection\` to scaffold a new data type with TypeScript interface, accessor, and React hook in one step.

When \`add_page: true\` is set, the tool also:
- Creates \`src/app/dashboard/{name}/page.tsx\` with a full CRUD DataTable and create dialog
- **Automatically adds a sidebar navigation entry** in \`src/lib/constants.ts\` — the new page will appear in the dashboard menu immediately, no manual edits needed
- Updates \`varity.config.json\` with the new collection name
- **Relational dropdowns auto-generated:** If any field name ends in \`Id\` (e.g., \`clientId\`, \`projectId\`), the generated page automatically creates a relational \`<Select>\` dropdown for that field — it calls the related collection's hook to populate the options and renders the related record's name instead of the raw ID in the table. See **Example 6 (Relating Two Collections)** in \`varity://sdk/database\` for the full pattern and the \`clientMap\` rendering technique.

The tool response confirms this: look for \`"✅ Sidebar navigation updated"\` in the \`next_steps\` array, and \`"src/lib/constants.ts"\` in \`files_modified\`.

**Auto-selected sidebar icons:** \`varity_add_collection\` picks an icon automatically based on the collection name (e.g., \`clients\` → \`tag\`, \`deals\` → \`trending_up\`, \`reports\` → \`chart\`, \`members\` → \`people\`). Business-entity collections like \`clients\`, \`contacts\`, and \`customers\` receive \`tag\` to avoid visual duplication with team/user collections that use \`people\`. To change the icon, edit the generated \`NAVIGATION_ITEMS\` entry in \`src/lib/constants.ts\`. See the full list of valid icon values in the Constants Pattern section above.

### If a collection name already exists

The SaaS template ships with pre-built collections: \`projects\`, \`tasks\`, \`teamMembers\`, \`userSettings\`. If you try to add one of these names with different fields, you'll see a \`COLLECTION_EXISTS\` error.

**Options when you hit a name collision:**

1. **Use the existing collection** — it may already support your use case. Check \`src/types/index.ts\` for existing fields, then import the hook:
   \`\`\`ts
   import { useProjects } from '@/lib/hooks';
   \`\`\`

2. **Use a more specific name** — instead of \`projects\`, use \`client_projects\` or \`budget_items\`:
   \`\`\`
   varity_add_collection({ name: "client_projects", fields: [...] })
   \`\`\`

3. **Extend the existing type manually** — add your extra fields directly to \`src/types/index.ts\` and \`src/lib/database.ts\`. The interfaces and accessors are plain TypeScript — edit them like any other file.

The \`COLLECTION_EXISTS\` error response includes a diff of existing vs. requested fields to help you decide which option fits best.
`;
